### ISSUE TITLE
How to add multine string options via CLI?

### ISSUE THREAD

**Issue by trompx** [WP2Static/static-html-output-plugin#1]
Hello @leonstafford,

While I can crawl / detect  and generate a zip archive of my website from the plugin admin page, I have problems running wp2static from the cli.

Running `wp help wp2static` outputs:
```
SUBCOMMANDS
  deploy
  diagnostics
  generate
  microtime_diff
  options
```

And `wp wp2static detect` gives `Error: 'detect' is not a registered subcommand of 'wp2static'`.
Any idea why the cli commands are not available (I checked if they have been moved to addon but didn't find anything on the other repos).

Wp2static : version 6.6.7 from https://downloads.wordpress.org/plugin/static-html-output-plugin.6.6.7.zip
Wordpress running on **sqlite** db, inside docker.

**Doc enhancement**
I found the doc was a bit lacking when trying to configure wp2static from cli.
I found good info at https://github.com/WP2Static/wp2static/blob/master/src/CLI.php.
Especially to list all options with `wp wp2static options list --reveal_sensitive_values`
Maybe adding this to doc could help others.

If I may, any idea how to set the `excludeURLs` from the command line for multiple excludes?

**Comment by leonstafford** [comment]
@trompx I've moved this to v6 repo, where we'll continue to maintain v6, as it's quite different from v7, including those WP-CLI commands. 

What have you tried for setting the excludes via WP-CLI? If you set via UI and then check how it's stored in DB, we just need to get it in the same way, I think it may be comma delimeted, but need to check

**Comment by leonstafford** [comment]
@trompx the readme of this GitHub repository should reflect V6 WP-CLI commands

**Comment by trompx** [comment]
Alright no problem.
As far as I remember I tried to no avail:
`wp wp2static options set excludeURLs /folder1 /folder2`

As on the GUI there was a line break for each entry, I supposed \n could work but no.
`wp wp2static options set excludeURLs /folder1\n/folder2`

Comma delimited doesn't work either, when I list values both are on the same line, while when I set them via GUI they appear on different lines (kind of beaking the terminal array)
`wp wp2static options set excludeURLs /folder1,/folder2`

**Comment by leonstafford** [comment]
Checking the database, in `wp_options` table, the excludeURLs are appearing with newlines as:

```
"excludeURLs" : "/wp-content/themes/twentyseventeen/banana.jpg                                                                     
/my_pricelist.pdf                                                                                                       
.js" 
```

which led to trying

```
$ wp statichtmloutput options set excludeURLs "$( cat /tmp/mylines.txt )"                                                                                                                                      
$ wp statichtmloutput options get excludeURLs                             
line1
line2
line3
```

and checking UI:

![screenshot_1590419801](https://user-images.githubusercontent.com/2066833/82825429-c249f380-9e9a-11ea-94fc-5506a50a3f44.png)

So we have a solution, sorry it isn't documented, but will remember this and add it to some examples, as I'll be using it myself in some automated tests in near future, as part of setting up specific sites + plugin configurations for testing.
