### ISSUE TITLE
Wrong export on Windows

### ISSUE THREAD

**Issue by fregante** [WP2Static/static-html-output-plugin#106]
The site is hosted on IIS, you can download the latest export here: https://roalmusic.it/wp/wp-content/uploads/wp-static-html-output-1592343040.zip

These are the contents of the zip, you can see the paths are completely incorrect, so I can't deploy this to Netlify (or anywhere, really)

<img width="452" alt="" src="https://user-images.githubusercontent.com/1402241/84831262-538c3000-b02b-11ea-9f4c-ccea5fcb10f4.png">

**Comment by leonstafford** [comment]
similar to https://github.com/WP2Static/static-html-output-plugin/issues/23

@fregante Windows support has been trailing for some time. I do have a Windows machine to test on now, though, so possibly can get this sorted before upcoming release. 

In the meantime, if you're running or willing to run Docker (and will need bash/some WSL, Cygwin or such), you can try this new project I started for local WP development on Windows/Mac/Linux: https://lokl.dev

This is a different project which may work to get your zip out on Windows: https://github.com/WP2Static/simplerstatic/files/4638814/simplerstatic-0.2.zip (updated fork of SimplyStatic plugin).

Basically, the plugin relies a lot on string replacements for path rewriting and hasn't been developed/tested frequently on Windows environments. I'll do my best to try and get that sorted for this next release, but the quickest workaround for you is to run a webserver that uses Unix filepaths, so anything Docker based for Windows should work like that (but there are challenges with Docker setups, too, so possibly Windows Subsystem for Linux with Apache/Nginx would be better).

Also, I see the `roalmusic.it/wp` - it will make like easier if you host on the domain root, not a subfolder, more issues for rewriting issues with a subdirectory hosted WP. 

Please let me know if any of that needs more explanation

**Comment by leonstafford** [comment]
tracking in duplicate issue https://github.com/WP2Static/static-html-output-plugin/issues/23

**Comment by fregante** [comment]
I’m actually a macOS user and I usually use Linux, but this hosting had an offer for Windows so I gave it a go. The point was to have the site available on a secondary domain so that the owner (not me) could update it as usual and deploy it to a static hosting. 

Lokl looks interesting and I saw SimplierStatic too, but I was interested in the automatic netlify upload.
