### ISSUE TITLE
Error while installing ver 6.6.20

### ISSUE THREAD

**Issue by nhhau** [WP2Static/static-html-output-plugin#108]
Hi Leon,
Trying to install the ver ver 6.6.20 and got this error
https://www.dropbox.com/s/nu3qqi1rdquz4c1/2020-06-17_14-10-04.png?dl=0

**Comment by nhhau** [comment]
never mind, i can install now

**Comment by leonstafford** [comment]
Hi @nhhau,

No worries, glad you got it sorted!

You will have seen that the releases page offers multiple archives. The default GitHub .zip and .tar.gz are a snapshot of the code at a point in time. The zip which I add is a pre-built installer zip, ready to upload to WordPress.

You can use the code directly from this repository, but then it will need to either be built or compiled for use:

 - `composer install` <- this will pull in all dependent libraries for the project, including for testing/development
 - `composer install --no-dev` <- this will pull in just dependent libraries for using the project
 - `composer build INSTALLERNAME` <- this will build a zip file, like the one I attach to releases

Being able to run the latest code from GitHub is useful to get familiar with, as there may be some benefits/bug fixes which aren't in the official wp.org release yet.

I'm glad to see you using GitHub and please don't hesitate to report any issues you find when exporting a site. Mike has a lot of sites, so it's good if you can report any issues you find trying to export any of them and I'll try to provide a fix ASAP.

There's also a support forum here, in case you have anything else you want to discuss: https://staticword.press

Cheers,

Leon
