### ISSUE TITLE
Support AWS EC2 IAM

### ISSUE THREAD

**Issue by wderezin** [WP2Static/static-html-output-plugin#12]
When deploying to AWS S3 make the IAM credential information optional.  I have my Wordpress server deployed in AWS EC2 with an IAM instance profile (role) which has the required access needed to deploy to AWS S3. 

I get the following error when trying to deploy without the Key/Secret.

```
Please input an S3 Key in order to authenticate when using the S3 deployment method.
Please input an S3 Secret in order to authenticate when using the S3 deployment method.
```

**Comment by leonstafford** [comment]
Tracking under same issue as https://github.com/WP2Static/static-html-output-plugin/issues/14
