### ISSUE TITLE
Failing to find files in 'dist' when exporting to S3/Zip with Bedrock

### ISSUE THREAD

**Issue by jacubsmith** [WP2Static/static-html-output-plugin#13]
Hey,

I'm having a bit of an issue getting the export functionality working for zip/s3 with the plugin. I was able to get it working with a subdirectory following guides found on other issues but the export is where it is failing. 

I believe it could be to do with me using the Bedrock folder structure from Roots.io or a failing in the exclude/include functionality.

With the folder structure all of the production assets live inside a dist file located here:
`/web/app/themes/theme_name/dist/`

I've tried adding this folder and specific files inside of the include URL section but have had no success. 

The plugin seems to be crawling the following folder:
`/web/app/themes/garrison/resources/`

Again I have added this to the exclude URL section but have had no success.

Is there a way I can specify a wildcard/regex expression for crawling files?

**Comment by leonstafford** [comment]
hardcoded filtering of `dist` paths was removed some time back, no longer an issue
