### ISSUE TITLE
Not rewriting URLs in main-sitemap.xsl

### ISSUE THREAD

**Issue by Zyles** [WP2Static/static-html-output-plugin#131]
Using a sitemap plugin to generate XML sitemaps, for example Rankmath causes a problem.

The sitemap XML requires the main-sitemap.xsl file. Once included in the build there are links that are pointing to the developer machine not the live urls.

The URLs in main-sitemap.xsl need to also be rewritten.

**Comment by leonstafford** [comment]
Hi @Zyles please try the build I linked in other issue's comment just now. That should be fixed there, if not, please reopen.
