### ISSUE TITLE
Netlify: Deployed failed while extracting zip: empty zip file

### ISSUE THREAD

**Issue by cnicodeme** [WP2Static/static-html-output-plugin#159]
Hi,

I'm trying to directly deploy my site to Netlify, but at Netlify, I get the following deploy failure:

> Deployed failed while extracting zip: empty zip file

I checked and generating the Zip for manual download works fine.

I'm using Wordpress v.5.5.3 with WP2Static vs 6.6.7.

**Comment by leonstafford** [comment]
@cnicodeme looks like an older version of plugin was being used. 

You'll want to switch to 6.6.23, which is available in source code from this repository or you can download from https://statichtmloutput.com (note the plugin name change from WP2Static, which is now a different approach to same plugin, with a newer Netlify deploy option you may want to test).
