### ISSUE TITLE
activation errors in php 8

### ISSUE THREAD

**Issue by leonstafford** [WP2Static/static-html-output-plugin#163]
in latest Lokl development:

```
PHP Fatal error:  StaticHTMLOutput\Options::__set(): Return type must be void when declared in /usr/html/wp-content/plugins/static-html-output/src/Options.php on line 139
Fatal error: StaticHTMLOutput\Options::__set(): Return type must be void when declared in /usr/html/wp-content/plugins/static-html-output/src/Options.php on line 139

```

**Comment by thegulshankumar** [comment]
Same here at XAMPP PHP 8.0

**Comment by thegulshankumar** [comment]
|Server architecture|Windows NT 10.0 AMD64|
|---|---|
|Web server|Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/8.0.0|
|PHP version|8.0.0 (Supports 64bit values)|
|PHP SAPI|apache2handler|
|PHP max input variables|1000|
|PHP time limit|120|
|PHP memory limit|512M|
|Max input time|60|
|Upload max filesize|40M|
|PHP post max size|40M|
|cURL version|7.73.0 OpenSSL/1.1.1h|
|Is SUHOSIN installed?|No|
|Is the Imagick library available?|No|
|Are pretty permalinks supported?|Yes|
|.htaccess rules|Your .htaccess file contains only core WordPress features.|


![image](https://user-images.githubusercontent.com/23408127/102764271-eaea8b00-43a0-11eb-9d00-a21a21a4f8ca.png)

**Comment by leonstafford** [comment]
Still few coding sessions away from sorting this out, sorry @thegulshankumar

**Comment by leonstafford** [comment]
[shop-php8-mulyadi.zip](https://github.com/leonstafford/static-html-output/files/6986564/shop-php8-mulyadi.zip)

This is a test build of the PHP 8 activation issue resolved, along with some other syntactical updates.
