### ISSUE TITLE
eicons not shown in export

### ISSUE THREAD

**Issue by ShadeWo** [WP2Static/static-html-output-plugin#21]
I apologise if this is too trivial, I just installed wp2static, exported a simple 1 page site, everything is well except for this detail: Eicons defined as 

`<i class="eicon-close"> ::before </i>` , where in css
`.eicon-close:before { content: '\e87f'; } `

...don't show up. Any quick workaround?

**Comment by leonstafford** [comment]
recently fixed in `master` branch, will be available in next wp.org release
