### ISSUE TITLE
Google api link being stripped

### ISSUE THREAD

**Issue by tchorst** [WP2Static/static-html-output-plugin#22]
Has anyone encountered link to both Googleapis and bootstrapcdn being stripped out? After processing, the src="" for both of these script calls are empty, when before they contained links to js files.
![Screen Shot 2019-07-10 at 4 03 03 PM](https://user-images.githubusercontent.com/6577960/61001012-b14cce00-a32c-11e9-92cf-ad90ef277e08.png)
<img width="1554" alt="Screen Shot 2019-07-10 at 4 04 33 PM" src="https://user-images.githubusercontent.com/6577960/61001013-b14cce00-a32c-11e9-91d7-5a48e4717ef1.png">

**Comment by leonstafford** [comment]
I've tested this with both an `https://` and `//` googleapis script tag and wasn't able to reproduce. Have recently done tidy up of this v6 codebase that may have fixed it. 

Added an extra test to the `isInternalLink` test to be safe. Please reopen if same issue persists and will look elsewhere for the offending code.

**Comment by leonstafford** [comment]
^ expected to be working in at least v6.6.9 onwards
