### ISSUE TITLE
Special Character Encoding

### ISSUE THREAD

**Issue by acketon** [WP2Static/static-html-output-plugin#24]
I'm running some tests of wp2static and running into issues where certain characters are not handled properly and end up garbled in the exported output. 

Version wp2static: `6.6.5`
Exporting site: http://www.bu.edu/bostonia/

Example content: 
http://www.bu.edu/bostonia/fall13/wine/

![image](https://user-images.githubusercontent.com/3139096/57173139-e69ee200-6df8-11e9-8ee9-1596767e5f10.png)

it seems curly quotes for instance end up as this: `â€™`

```
<p>In May 2012, with a decade of collecting under his belt, Blake (who requested that his real name not be used) went shopping online for some wines from Franceâ€™s vaunted Bordeaux and Burgundy regions. He contacted a high-end Manhattan retailer, and began receiving emails from the owner about choice wines for sale. â€œHe had all kinds of stuff that was really rare, old, and hard to find,â€ Blake recalls. â€œHe claimed he got everything from restaurants heâ€™d known for 25 years or from friends at the wineries. He told me great stories about where the wine came from.â€</p>
```

**Comment by thegulshankumar** [comment]
The latest [6.6.16](https://github.com/WP2Static/static-html-output-plugin/releases/tag/6.6.15) fixes the problem. 
Here's my test report: https://youtu.be/8pk4M1eSqLY
