### ISSUE TITLE
Long Dash Converted to "â&#128;&#148;"

### ISSUE THREAD

**Issue by stirtingale** [WP2Static/static-html-output-plugin#29]
When using Yoast Long Dash ( em-dash — ) titles are converted to 

Page Title **â&#128;&#148;** Site Title

<img width="531" alt="Screenshot 2019-05-02 at 17 47 05" src="https://user-images.githubusercontent.com/25981099/57092000-567e7100-6d02-11e9-8f41-7dad3a66313c.png">

**Comment by thegulshankumar** [comment]
This problem is resolved in the latest release 6.6.15 fixes the issue

**Comment by thegulshankumar** [comment]
Latest release fixes this problem.
