### ISSUE TITLE
[v6.6.7] CSS being parsed, rewritten, and causing issues due to CSS cascade (Workaround / Fix inside)

### ISSUE THREAD

**Issue by lukearmstrong** [WP2Static/static-html-output-plugin#3]
First off, this is a brilliant plugin, we've just used it for the first time on a project and are now hosting a WordPress site using AWS CloudFront and S3.

Whilst I'm aware that v7 is currently being worked on, and this is unlikely to be fixed for v6 (I have seen mentions that this is being fixed for v7) I thought I would describe the issue we had, and what I have had to do to prevent wp2static from rewriting our CSS.

I understand the reason for CSS to be parsed, is to re-write URLs that may be within, and I assume to do some basic minification by stripping whitespace and comments, though this actually resulted in the filesize of our webpack minified files being increased.

But I'd argue though that if someone is using absolute links `/wp-content/themes/theme-name/assets/images/background.png` within their CSS, then wanting to use WP2Static to relocate their assets folder to hide the fact that they are using WordPress. Then it is much simpler for them to switch to using relative links instead of the plugin modifying the files, so if their CSS file was in `/wp-content/themes/theme-name/assets/css/style.css` they would reference files like this instead: `../images/background.png`

We had an issue where our CSS had been parsed, and the order of statements had been changed, so the media queries had been written first, then statements not inside media queries were written afterwards. Whatever appears last in your CSS file is used if the selectors are equal, a media query does not appear to add any weight over a non-wrapped selector.

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#Conflicting_rules

So this re-ordering of the styles resulted in the browser allowing the styles not inside media queries (our "desktop" styles) taking precedence over our "mobile" styles, which then threw up a load of bugs when we went live because we had done all of our device testing on the WordPress site, not the static one. Derp.

# Workaround / Fix

To fix this, I downloaded the source code at this commit (the source code in the plugin folder is obfuscated):
[a71e5ca8114e678e8917f47b19ac200248dc5831](https://github.com/WP2Static/wp2static/tree/a71e5ca8114e678e8917f47b19ac200248dc5831)

This is the closest commit I can find to the `v6.6.7` release [as it is not tagged](https://github.com/WP2Static/wp2static/issues/538).

I copied the files from `plugin/` into the same folder in my WordPress plugins:
`wp-content/plugins/static-html-output-plugin/plugin/`

I then edited this file between lines 433-450:
`static-html-output-plugin/plugin/WP2Static/SiteCrawler.php`
https://github.com/WP2Static/wp2static/blob/a71e5ca8114e678e8917f47b19ac200248dc5831/plugin/WP2Static/SiteCrawler.php#L433-L450

I replaced the contents of the switch case with this instead:

```php
case 'css':
                $this->processed_file = $this->response;
                break;
```

(Deleting the whole `css` case block results in hitting `default` which does the same too, as you can see at [line 474](https://github.com/WP2Static/wp2static/blob/a71e5ca8114e678e8917f47b19ac200248dc5831/plugin/WP2Static/SiteCrawler.php#L474) ).

This prevents the CSS from being processed by the [Sabberworm\CSS](https://github.com/sabberworm/PHP-CSS-Parser) library, and just uses the CSS file as is, it will be up to you to ensure you are using relative links if you want to ensure this workaround / fix works for you.

**Comment by leonstafford** [comment]
fixed today in `master`, now CSS is only parsed in order to extract URLs, but not using it's output to generate the CSS, only doing basic string replacements on CSS files to modify URLs. @lukearmstrong you should be all good now if using from this repo. It will be available in GitHub release 6.6.14 or later and next wp.org update
