### ISSUE TITLE
Clear deploy cache through WP-CLI

### ISSUE THREAD

**Issue by hiranthi** [WP2Static/static-html-output-plugin#31]
While the WP-CLI integration does allow us to generate / deploy our WP2Static website it currently isn't possible to clear the deploy cache before generating / deploying. 

Which means that (when wanting to do a 'fresh' deploy) it's mandatory to log into the WordPress dashboard, go to the WP2Static settings and manually clear the deploy cache before re-generating / deploying.

Ideally it'd be possible through WP-CLI with its own subcommand (ie. `clearcache`) and/or as an extra parameter (ie. `--clear`).

**Comment by leonstafford** [comment]
Hi @hiranthi sorry for the late reply. This is available in version 7 latest pre-release, which is what the website docs on WP-CLI usage currently refer to.

Moving this to a new repo where we'll fix these things and continue to maintain v6 (quite divergent codebase, so splitting into own project)

**Comment by leonstafford** [comment]
@hiranthi I've just put this feature into 6.6.9 development codebase, so should be in next build of this (Static HTML Output plugin).
