### ISSUE TITLE
Adding multiple additionalUrls through cli does not work (6.6.5)

### ISSUE THREAD

**Issue by jalbstmeijer** [WP2Static/static-html-output-plugin#33]
Hi,

Trying to add multiple urls to additionalUrls though the cli does not work.
All ways of trying to add a new line, get escaped ending up as string in the gui.

in the database it looks like this when added through the gui:

\"url1\r\nurl2\"

using the cli

wp wp2static options set additionalUrls 'url1\r\nurl2'

you get
\"url1\\r\\nurl2\"

so the newline gets escaped

I saw an example online (https://developer.wordpress.org/cli/commands/option/update/)

wp option update my_option < value.txt

not sure if that would help.
but the wp2static cli options  does not have an "update" option and "set" expects a value

Gr, J

**Comment by leonstafford** [comment]
ah, that will teach me to not check all issues for months!

Same as this issue: https://github.com/WP2Static/static-html-output-plugin/issues/1

The 
```
wp statichtmloutput options set additionalUrls enter some{carriage return}
enter more
and some more
```
by @vls29 is a lot easier :)
