### ISSUE TITLE
Additional HTML added when static site is exported to local subdirectory

### ISSUE THREAD

**Issue by blu-regard** [WP2Static/static-html-output-plugin#35]
When attempting to export the site in a sub directory within wordpress some areas of the website are covered with bizarre tags not found in other parts of the website such as code, s, and strike. This happens when all the options in the plugin are set to default.

**Comment by leonstafford** [comment]
should no longer be an issue, though was likely due to clashes between the web dir name, site URL and deployment URL  during URL rewriting process. safest is to use different naming, such as 

 - `/var/www/wpsiteblah`
 - `https://devsiteblah.com`
 - `https://devsitelive.com
