### ISSUE TITLE
Exported site has wrong characters (codepage issues)

### ISSUE THREAD

**Issue by tobkle** [WP2Static/static-html-output-plugin#37]
It generates...
```html
<html lang="de-DE">
```
...with that it doesn't show icon font.
...with that it does better...
```html
<html lang="de">
```

Additionally it doesn't handle German special characters well:  öäüß
it prints...
```html
BurgstraÃŸe 3
```
instead of...
```html
Burgstraße 3
```

**Comment by leonstafford** [comment]
fixed in commit to `master` today, will be in next release
