### ISSUE TITLE
Footer Placement Issue

### ISSUE THREAD

**Issue by thegulshankumar** [WP2Static/static-html-output-plugin#43]
Thank you for creating with WordPress. This message is generally suppose to come in footer but going inside plugin UI.

![image](https://user-images.githubusercontent.com/23408127/82210376-9c699f80-992c-11ea-8713-6f0640f38f48.png)

**Comment by leonstafford** [comment]
most likely fixed by this yesterday: https://github.com/WP2Static/static-html-output-plugin/commit/2bb1683a13caa406e73a32666d450c847f6ee909

I'd forgotten to include CSS in the build, it came after the 6.6.8 build, so will be fixed in next
