### ISSUE TITLE
List of changes happens in HTML after Export

### ISSUE THREAD

**Issue by thegulshankumar** [WP2Static/static-html-output-plugin#47]
1. HTML entity is getting replaced with real HTML causing break of preformatted code

By default WordPress output source code like this
```
<pre class="wp-block-preformatted"><code>&lt;div class="gcse-searchbox-only"&gt;&lt;/div&gt;</code>
<code>&lt;div class="gcse-searchresults-only"&gt;&lt;/div&gt;</code></pre>
```
But export comes with source code like this
```
<pre class="wp-block-preformatted"><code><div class="gcse-searchbox-only"></div></code>
<code><div class="gcse-searchresults-only"></div></code></pre>
```

**Line 192**:  https://www.diffchecker.com/jpiLMsd6

**Processing > Remove cruft >**

1.   **Remove WP <link> tags** when checkbox enabled it removes link hreflang, canonical tag as well

2. **Remove HTML comments**  when checkbox enabled it removes IE conditional tag from the footer

```
<!--[if lte IE 11]>
<script   type='text/javascript' src='https://example.com/wp-content/cache/asset-cleanup/js/item/generate-classlist-vc9844c358ef928354aa6a56dbdeb9c3ac1a9fed4.js'></script>
<![endif]-->
```

**3. Relative URL assests missing with non-existing hosname**

```
https://placeholder.wpsho/wp-content/themes/twentytwenty/assets/fonts/inter/Inter-upright-var.woff2 net::ERR_NAME_NOT_RESOLVED
(index):1 GET https://placeholder.wpsho/wp-content/plugins/social-icons-widget-by-wpzoom/assets/font/socicon.woff net::ERR_NAME_NOT_RESOLVED
```

- To repro, add these plugins in your local site
![image](https://user-images.githubusercontent.com/23408127/82414474-bb834100-9a94-11ea-9889-4c4f13d31497.png)

**Sample 1**: from `/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=5.1.9` below ajax-loader.gif return 404

```
div.wpcf7 .ajax-loader {
	visibility: hidden;
	display: inline-block;
	background-image: url('../../images/ajax-loader.gif');
```
**Sample 2**: Missing file `/wp-content/plugins/social-icons-widget-by-wpzoom/assets/font/socicon.ttf`

**4. Changes in CSS element** changing from
```
.socicon-500px:before {	
    content: "\e056"	
}
```
To

`.socicon-500px:before {content: "";}`

Affected path: `/wp-content/plugins/social-icons-widget-by-wpzoom/assets/css/socicon.css`

Difference report: https://www.diffchecker.com/563VmMuK

That's all for now. Thanks for looking into this.

**Comment by leonstafford** [comment]
@thegulshankumar , looking into. The `canonical` and `alternative` are quickly fixed. 
 
How about these other `<link>` tag types, which do you consider must-haves and which can continue to be removed?

```
                 'shortlink',                                                    
                 'pingback',                                                     
                 'EditURI',                                                      
                 'wlwmanifest',                                                  
                 'index',                                                        
                 'profile',                                                      
                 'prev',                                                         
                 'next',                                                         
                 'wlwmanifest', 
```

**Comment by leonstafford** [comment]
And any other common WP ones you think should be stripped by default not in the list above?

**Comment by leonstafford** [comment]
note, the plugin is currently also removing any `<link>`s with `.w.org` within the  `rel` attribute of `<link`> when that option is checked

**Comment by thegulshankumar** [comment]
Thanks for fixing it. 

Please remove all that you have listed in last comment, except `prev `& `next` (Well, Google doesn't use but other search engine might be using).

I am not sure what do you mean by `index` <link> tag.

**Comment by leonstafford** [comment]
the `index` is mentioned here: https://www.w3.org/TR/html4/types.html#type-links

**Comment by thegulshankumar** [comment]
Yet, I have not seen that in WordPress. We can ignore that.

**Comment by leonstafford** [comment]
hmm, looking at the next/prev usage and that it won't affect indexing for sites, I'll continue to have it removed when ppl check that option. If there's enough demand to make it separately configurable, that can happen (ie, accessibility for sites designed that way). The purpose of this option in the plugin is to remove a lot of the page bloat that WP still dumps out that people didn't ask for.

In WP2Static, when it comes time to release the Advanced HTML Processor, there would likely be a filter for easier selection of specific elements to remove.

**Comment by thegulshankumar** [comment]
Please make sure to preserve these as well

 rel="preload"
rel="preconnect"
"shortcut icon"
rel="icon"

**Comment by thegulshankumar** [comment]
Popular plugin such as RankMath, except Yoast consider adding rel="next", rel="prev" so I think it's worth keeping or leaving optional.

**Comment by leonstafford** [comment]
related https://github.com/WP2Static/static-html-output-plugin/issues/48

**Comment by leonstafford** [comment]
@thegulshankumar this test shows a bunch of potential `link`'s and the ones that now get removed: https://github.com/WP2Static/static-html-output-plugin/commit/79c9b94c2cd4440a3feed55195e9a5586dc4604e#diff-bf693312faa9d0d8873817941635443cR640

**Comment by thegulshankumar** [comment]
I don't think wlwmanifest is needed. It is `used by Windows Live Writer`. It has no use for Public static site.

**Comment by thegulshankumar** [comment]
I hope wlwmanifest also get removed from static output.

**Comment by leonstafford** [comment]
re the conditional IE comment tags, I am pretty sure I made a conscious decision to remove those as part of comment tag removal, but will check. The option for "Remove conditional comments within HEAD" is specifically for within the head, so I think you can choose to preserve those specifically, but not the ones in the body, if using the "Remove HTML comments" options, will confirm behaviour and add tests to confirm. If it's that we can't remove HTML comments without also removing those pseudo comments to target IE, I'm fine with also removing those. IE deserves no favors regarding compatibility in this world.

**Comment by leonstafford** [comment]
For contact form 7, is it actually usable with WP Serverless forms or other solution for making it play nice with static? I'll still use the example code to test rewriting behaviour, but don't think there's any use in CF7's ajax call in static site.

To reproduce your code sample, any steps for Cf7 and Widgets plugin you linked or just activate and stick on a page?

**Comment by thegulshankumar** [comment]
"IE deserves no favors regarding compatibility in this world." That's some bold statement. Please leave that AS IS. Let's focus on the next important issue.

**Comment by thegulshankumar** [comment]
To reproduce CF7 issue > simply Install and activate plugin > add its Shortcode in your Contact page.

**Comment by thegulshankumar** [comment]
I am not a huge fan of CF7, it is just a example to repro a common issue that's widespread for other stuffs as well. Precisely speaking, when absolute path not present but relative then resources break.

**Comment by leonstafford** [comment]
Cool, thought so. Am able to see the social assets issue, too. Will start on fixes

**Comment by leonstafford** [comment]
OK, good, so for those assets, it's a detection/crawling problem, not a rewriting issue, so good area to improve (following/including assets within linked stylesheets. Including them should be easy first improvement Rewriting them won't be needed for standard settings, but will need more work to ensure they are rewritten to target format (relative, offline URLs, etc), so may defer that part if they at least get included normally.

**Comment by thegulshankumar** [comment]
Simpler Static doesn't miss such path, Can you get some hints how it is making things work?

**Comment by leonstafford** [comment]
each works a bit differently. I'm experimenting with something a bit different again for Static HTML Output now to address this...

**Comment by leonstafford** [comment]
looks promising solution so far.. just missing that ttf at the moment and should be sortable

![screenshot_1589993221](https://user-images.githubusercontent.com/2066833/82473766-9654f980-9ab9-11ea-81c1-091b28056486.png)

**Comment by leonstafford** [comment]
![screenshot_1589993342](https://user-images.githubusercontent.com/2066833/82473956-d9af6800-9ab9-11ea-9680-8b4fe1361bb6.png)

That would be why :P may be my server not serving ttf's or actually missing, but this solution looks good, so will think on it a bit and adjust some other things... this may be the biggest improvement to this plugin for first time users..

**Comment by thegulshankumar** [comment]
Great! Once a new build is ready, I would be happy to test it.

**Comment by leonstafford** [comment]
[wp-static-html-output-1589994152.zip](https://github.com/WP2Static/static-html-output-plugin/files/4658284/wp-static-html-output-1589994152.zip)

not a github tagged release there, but very keen to see what you find testing it, for theme/plugin asset detection success

**Comment by leonstafford** [comment]
[static-html-output-plugin-gulshan-new-css-methods.zip](https://github.com/WP2Static/static-html-output-plugin/files/4658292/static-html-output-plugin-gulshan-new-css-methods.zip)

right file there ;)

**Comment by thegulshankumar** [comment]
Great work! Regarding background elements things are fine (as tested for offline ZIP)

I am double checking.

**Comment by leonstafford** [comment]
Excellent! It wasn't a lot of work, just a slight change in concept + small fix in CSS processing.

I haven't done any offline zip testing for a while, but it's had bugs for a while and will probably still need some fixing

**Comment by thegulshankumar** [comment]
My theme is adding Google Fonts. 
<link rel="stylesheet" id="generate-fonts-css" href="//fonts.googleapis.com/css?family=Open+Sans:300,regular,italic,600,700" type="text/css" media="all">
In case of offline .zip it loads this way 
```
file://fonts.googleapis.com/css?family=Open+Sans:300,regular,italic,600,700
```
Causing intial delay of 15-17 seconds in rendering of web page.

Forcefully, adding https:// protocol from plugin side can fix.

**Comment by leonstafford** [comment]
yeah, for offline, will need to add some code to replace any protocol-relative URLs with https, which in itself should be fairly quick fix. I'm suprised that's the only issue with offline :P 

For regular deployments - no missing URLs now?

**Comment by thegulshankumar** [comment]
In online web page browser can follow document protocol. 
Indeed, offline need special hint to use `https://` instead `file://`
Simple issue.

**Comment by leonstafford** [comment]
so, for the `<code>` entity decoding, there's code that was submitted by a user some time ago, to twice force html decoding as a solution for text encodings. It's quick to disable that and get the `<code>` blocks preserving entities properly, but I need to investigate that I don't undo the solution the other code is doing at the same time...

**Comment by thegulshankumar** [comment]
Live demo:  https://gksingapore.b-cdn.net/
Background Images & Social Icon looks good.  https://gksingapore.b-cdn.net/

I double checked with and without AO plugin. 

After code block, last this one is an issue. 

![image](https://user-images.githubusercontent.com/23408127/82480504-86590c00-9af1-11ea-943f-1689fa508e53.png)

**Comment by leonstafford** [comment]
ok, great, thanks! 

will be nice to solve that one if possible. If I recall prior discussion, it was pointing towards the CSS parsing library and didn't have a solution, but I have an idea as I type that should solve it (use CSS parsing just for link extraction, but only simple string replacements for rewriting URLs in the CSS, so we don't end up with this funkiness.

**Comment by leonstafford** [comment]
@thegulshankumar hopefully this build fixes the CSS and HTML entities issues. The HTML one may bring back some issues with Unicode sites, but the workaround I removed to fix preserving html entities wasn't a proper fix anyway, so will look at proper multilingual support in future.

[gulshan6.6.14test.zip](https://github.com/WP2Static/static-html-output-plugin/files/4661604/gulshan6.6.14test.zip)
