### ISSUE TITLE
Missing "ver" query argument on stylesheets

### ISSUE THREAD

**Issue by crstauf** [WP2Static/static-html-output-plugin#5]
I use WordPress' asset versioning system to bust cache on the dynamic version of my site, and noticed that the `ver` query arg appears to be removed (it's in the source of the dynamically-generated page, but not in the source of the WP2Static generated site).

Note: the `ver` argument does get includes for external JavaScript files.

**Comment by leonstafford** [comment]
@crstauf shouldn't be an issue in V7. Moved to this repo to track V6 issues, so we can start fixing and maintaining for users unable to move to V7 yet

**Comment by crstauf** [comment]
Thanks, @leonstafford!
