### ISSUE TITLE
Cannot force to include wp-json content

### ISSUE THREAD

**Issue by wrobelda** [WP2Static/static-html-output-plugin#6]
I am trying to export a website that includes jQuery, which in turn reads content from wp-json, e.g. wp-json/wp/v2/pages/15

The log file insists to exclude the wp-json, which I wasn't even able to understand from your commit history the reasoning behind, but either way I attempted to forcefully include them. 

On the settings page it is said next to "Exclude" section that 

> This will be applied after any exclusions, in case you want to exclude a whole directory, then include just one file from it."

Yet they still get excluded:

```
Exclusion rules wp-json
Excluding /wp-json/wp/v2/pages/30 because of rule wp-json
Excluding /wp-json/wp/v2/pages/15 because of rule wp-json
```

EDIT: I copied the exported JSON files manually yet the content is still not showing up on the site, so I presume the issue is elsewhere. FYI I am using Lay Theme.

**Comment by leonstafford** [comment]
@wrobelda this is now not forcefully excluded within the plugin for this `master` branch of the plugin. 

Export log for TwentyTwenty now shows 

```
200       /wp-json/   Note: discovered on: / 	
400       /wp-json/oembed/1.0/embed   Note: discovered on: / 	
```

which should allow for your custom JSON page endpoints to work again. 

This will be available to use in next release
