### ISSUE TITLE
Relative path, base href not showing, should not include DNS Prefetch for Localhost

### ISSUE THREAD

**Issue by thegulshankumar** [WP2Static/static-html-output-plugin#60]
I have enabled
![image](https://user-images.githubusercontent.com/23408127/82636804-13e74980-9c21-11ea-8501-c92e30e9190d.png)

**Video**: https://youtu.be/1a4Pyaxo5eU

Enabling Remove WP <link> tags remove one link, still leave localhost footprint

From
```
<link rel='dns-prefetch' href='//gulshan.localhost' />
<link rel='dns-prefetch' href='//s.w.org' />
```
To
```
<link rel='dns-prefetch' href='//gulshan.localhost' />
```

I further checked where I found core includes by default in case of localhost
![image](https://user-images.githubusercontent.com/23408127/82637641-d388cb00-9c22-11ea-86ef-8285f7f7dbc9.png)

**Comment by leonstafford** [comment]
Please try this one. I wasn't able to reproduce the issue, may have been due to Relative URL option

[testprefetchissuegulshan.zip](https://github.com/WP2Static/static-html-output-plugin/files/4675212/testprefetchissuegulshan.zip)

**Comment by leonstafford** [comment]
and to confirm, WP's Site URL was set to `http://gulshan.localhost` ?

**Comment by leonstafford** [comment]
ah, I see the `:4067`, was that also in Site URL setting or just the gulshan.localhost?

**Comment by leonstafford** [comment]
no code change, but added test to confirm current behaviour. 

need to add to requirements of plugin:

WordPress Site URL matches address you use to access site, one of:

 - http://localhost (implied port 80)
 - https://localhost (implied port 443)
 - http://localhost:1234 (specify port)

**Comment by leonstafford** [comment]
@thegulshankumar I'm not 100% convinced about this one, but if you can reproduce, let's reopen
