### ISSUE TITLE
Double slashes for assets

### ISSUE THREAD

**Issue by JuliaUsanova** [WP2Static/static-html-output-plugin#61]
The output looks mostly fine exept the double slashes for assets:
<img width="1655" alt="Screen Shot 2020-05-22 at 10 48 27" src="https://user-images.githubusercontent.com/2921176/82645405-805f4a00-9c1b-11ea-9334-4c047dd9b84d.png">

The source plugin structure is like this:
<img width="460" alt="Screen Shot 2020-05-22 at 10 49 21" src="https://user-images.githubusercontent.com/2921176/82645472-9967fb00-9c1b-11ea-9b7e-8cff759ed2ca.png">

Plugin sources are fetched line this:
<img width="1036" alt="Screen Shot 2020-05-22 at 10 13 30" src="https://user-images.githubusercontent.com/2921176/82645584-c74d3f80-9c1b-11ea-9967-2535a5424afd.png">

I cannot share sources here as it is a commercial project, but if you are interested in specific files, let me know, I'll share

PHP Version: 7.3
WordPress Version: 5.4.1

Looking forward to hearing from you!

**Comment by thegulshankumar** [comment]
Hi, except these two plugins, does static assests load from other plugins?

**Comment by JuliaUsanova** [comment]
we don't have much ui plugins. Seems like those only

for main site content looks mostly good:
https://d1s39xurrphbq3.cloudfront.net/index.html

for subsite there are also some files missing, even though I've added paths for them manually:
https://d1s39xurrphbq3.cloudfront.net/nl/index.html

**Comment by thegulshankumar** [comment]
Okay, 

- Please make sure you're using [latest build 6.6.15](https://github.com/WP2Static/static-html-output-plugin/files/4664167/static-html-output-plugin-6.6.15.zip) of this plugin.
- Is your Development site load these assests from normal URL or that also contains double slash? (Just asking) 
- Does site appears fine if you choose other deployment method, I recommend testing with BunnyCDN. (They include 14 days free trial)

I have never seen this problem before. That's why may I suggest trying a different plugin
https://wordpress.org/plugins/social-icons-widget-by-wpzoom/
When I tested last time, assests were loading properly.

Thanks

**Comment by JuliaUsanova** [comment]
* I'm using the latest build
* I don't have Development site, as we make changes on wpengine development environment
* Will try BunnyCDN

https://wordpress.org/plugins/social-icons-widget-by-wpzoom/ is for another purpose, on our site carousel plugin is broken

**Comment by thegulshankumar** [comment]
At 'wpengine development environment' does your site appears with or without double slash? Please check that first.

**Comment by thegulshankumar** [comment]
I know that plugin is for another purpose. What I mean that plugin add some CSS and JS or any other plugin you can try to see how it load in dev site and static version? This is to confirm if those two plugins have bug or this plugin.

**Comment by JuliaUsanova** [comment]
Oh, it's with double slashes. Thank you for the hint!

**Comment by thegulshankumar** [comment]
It appears S3 doesn't allow loading resources with double slash. However, BunnyCDN does so you may like to try it or check with that plugin author if they can release a fix.

**Comment by JuliaUsanova** [comment]
okay, thank you for your assistance!

**Comment by leonstafford** [comment]
@JuliaUsanova - glad you narrowed the issue down and that it's more to do with source site/plugins. 

I'll close this issue as related to this plugin. If you're still stuck on that double-slash issue, looks like these are the developers: https://divicake.com/products/divi-carousel-module/

And you may have luck in a Divi official/unofficial FB group - I'm not on FB, but those groups tend to be large and people to help
