### ISSUE TITLE
Encoded localhost URL need to replace with Deployment address

### ISSUE THREAD

**Issue by thegulshankumar** [WP2Static/static-html-output-plugin#65]
Hi,

Live:  https://gk-socialshare.netlify.app/

* Click on any sharing button (e.g, Facebook)
![image](https://user-images.githubusercontent.com/23408127/82859030-32a45380-9f33-11ea-9cd9-6c994775dea1.png)

* It will take you to page ...

```
https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fsocialsharing.localhost%3A4552%2F
```

![image](https://user-images.githubusercontent.com/23408127/82859165-9f1f5280-9f33-11ea-9296-259e8cd80f3a.png)

* However, expected sharing path is 

```
https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fgk-socialshare.netlify.app%2F
```

Thanks

**Comment by leonstafford** [comment]
From Sassy Social Sharing plugin. Original source example:

```html
<li class="heateorSssSharingRound"><i style="width:35px;height:35px;border-radius:999px;" alt="Facebook" Title="Facebook" class="heateorSssSharing heateorSssFacebookBackground" onclick='heateorSssPopup("https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%2Fsassytest%2F")'><ss style="display:block;border-radius:999px;" class="heateorSssSharingSvg heateorSssFacebookSvg"></ss></i>
```

expected output (if deployment URL is https://example.com):

```html
<li class="heateorSssSharingRound"><i style="width:35px;height:35px;border-radius:999px;" alt="Facebook" Title="Facebook" class="heateorSssSharing heateorSssFacebookBackground" onclick='heateorSssPopup("https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fexample.com%2Fsassytest%2F")'><ss style="display:block;border-radius:999px;" class="heateorSssSharingSvg heateorSssFacebookSvg"></ss></i>
```

Quick solution: add another broad rewrite rule for encoded version of WP site URL (including port if custom) to destination URL, including force https rewrite if destination protocol is https

**Comment by leonstafford** [comment]
@thegulshankumar this build should include the fix

[65encodedrewrites.zip](https://github.com/WP2Static/static-html-output-plugin/files/4684099/65encodedrewrites.zip)

**Comment by thegulshankumar** [comment]
* A slash is missing while sharing blog post

* Homepage is fine.

![image](https://user-images.githubusercontent.com/23408127/82937934-a172c280-9fae-11ea-81a6-4920f9785df4.png)

**Comment by leonstafford** [comment]
- [ ] add inner page path to test

**Comment by leonstafford** [comment]
@thegulshankumar this build should fix the above issue

[statichtmloutput65encodedrewrites.zip](https://github.com/WP2Static/static-html-output-plugin/files/4711751/statichtmloutput65encodedrewrites.zip)
