### ISSUE TITLE
Missing a background image

### ISSUE THREAD

**Issue by thegulshankumar** [WP2Static/static-html-output-plugin#66]
Hello!

The MusicBlog theme uses header background image which goes missing

`<div id="page-site-header" class="relative" style="background-image: url('https://bgimg.netlify.app/wp-content/themes/musicsong/assets/uploads/custom-header-image.jpg');">`

**Steps to repro**

* Create a localhost WP
* Use this [version](https://github.com/WP2Static/static-html-output-plugin/files/4677741/postspaginationtestfix.zip) of plugin
* Add this theme https://downloads.wordpress.org/theme/musicsong.1.1.9.zip
* Deploy
* You will find `/wp-content/themes/musicsong/assets/uploads/custom-header-image.jpg is missing`

**Live demo** https://bgimg.netlify.app/

**Logs**

* [Detected WordPress URLs](https://pastebin.com/raw/WUuehjFz)
* [Modified Crawl list](https://pastebin.com/raw/2p559xM8)
* [Discovered URLs during crawl](https://pastebin.com/raw/JkUN2bEA)
* [Crawled links](https://pastebin.com/raw/azYUKGeK)
* [404s encountered](https://pastebin.com/raw/wBNuHs35)
* [Export logs](https://pastebin.com/raw/riaNzVsU)

What is expected
![image](https://user-images.githubusercontent.com/23408127/82870410-858b0480-9f4d-11ea-8e86-d211dd6075d7.png)

What appears
![image](https://user-images.githubusercontent.com/23408127/82870459-9dfb1f00-9f4d-11ea-9c89-8643b8855a29.png)

Also it appears certain element (perhaps not used in DOM) appears missing from CSS assets

`/wp-content/themes/musicsong/style.css`

```
.frame-layout {
    background-image: url('assets/uploads/pattern.png');
}
```

Localhost address is stilling coming
![image](https://user-images.githubusercontent.com/23408127/82872600-e405b200-9f50-11ea-9a9a-6f0bd48800bd.png)

Thanks

**Comment by leonstafford** [comment]
adding multiple tests to cover:

 - rewriting of URLs within external and inline styles
 - detecting/extracting URLs from external and inline styles

**Comment by leonstafford** [comment]
@thegulshankumar in your `dns-prefetch` example above, where the hostname hadn't been rewritten, could you please confirm the original source code for that element in the dev site? (I'd like to know if it contains the port within the protocol-relative URL. If it doesn't, it's more of a WP issue, as `//domain:1234` is very different than `//domain`)

**Comment by thegulshankumar** [comment]
You are right. That happens with Port only. 

With normal `dev.example.com` it appears with production site URL
`<link rel="dns-prefetch" href="https://example.com">`

**Comment by leonstafford** [comment]
![screenshot_1591022769](https://user-images.githubusercontent.com/2066833/83420813-ad2f1080-a416-11ea-8aaf-141f9ee1a502.png)

Fixed. Area of code could definitely be improved for elegance, but this works and doesn't seem to break anything else. 

[statichtmloutput66missingbackgrounds.zip](https://github.com/WP2Static/static-html-output-plugin/files/4711913/statichtmloutput66missingbackgrounds.zip)

**Comment by leonstafford** [comment]
Note: the issue was due to the way the detected URL from an inline style (background-image in this case) was being added to the "Detected URLs" during first phase of crawling. It was not adding the URL as `/path/to/file.png`, rather `https://placeholder.wpsho/path/to/file.png`

**Comment by thegulshankumar** [comment]
This looks fixed now. Thanks Leon.
