### ISSUE TITLE
statichtmloutput_post_deploy_trigger  hook

### ISSUE THREAD

**Issue by Kammi638** [WP2Static/static-html-output-plugin#67]
I found that `statichtmloutput_post_deploy_trigger` doens't exist but `wp2static_post_deploy_trigger.` is working, but if i use this hook to trigger my git pipeline i have got error `Failed during "Performing post-deployment actions", please consult the Help tab for where to get assistance.`

This is my code. Am I doing something wrong or?  

```
function static_deploy_trigger($archive)
{
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, '<pipeline trigger>');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    echo $archive;
}

add_filter('wp2static_post_deploy_trigger', 'static_deploy_trigger');
```

i tried this too:
```
function static_deploy_trigger()
{
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, '<pipeline trigger>');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

add_filter('wp2static_post_deploy_trigger', 'static_deploy_trigger');
```

**Comment by leonstafford** [comment]
Thanks for reporting, @Kammi638 - I'll test and get back to you. The rename from `wp2static` to `statichtmloutput` isn't live in wp.org plugin yet, so should only be if you used from the source code here or got a recent release from this GitHub repository.

Besides that, code sample looks good. Will get back to you

**Comment by Kammi638** [comment]
Thanks for your response.
I don't care about hook name in fact. I will change this when you will update this in wp.org. Just reported that i found it. 
I will wait for your tests. Thank you!

**Comment by Kammi638** [comment]
I'm rly sorry.
It's looks like that is my local problem. I tried it on webserver and it works.
