### ISSUE TITLE
Upon selecting Remove WP tags, my <link rel="canonical" href="https://xyz.com"> gets deleted

### ISSUE THREAD

**Issue by osspl** [WP2Static/static-html-output-plugin#69]
Hi, I am facing an issue.

**If I select Remove WP tags, my Canonical tag is being removed** and if don't I get a bunch of nonsense tags that I don't need.

Could you please tell me a way to **get Canonical tags back after processing**?

Thanks :)

**Comment by osspl** [comment]
Thank You, Sir,

This new version did solve the problem of rel="canonical" but URL rewrite options didn't work, then I was able to fix that issue(remove the trailing / from the end - easy fix). 

After that, my theme gallery broke down completely & I went back to WP2Static plugin.

Is it possible for you to point me to me the exact few lines to add in WP2Static in order to get rel="canonical" as this new version is completely breaking my theme which l am not able to debug? 

If you have a hack like below that would also make my life quite easy.



Thanks for understanding, I owe you a beer/coffee for your contribution to the community.

**Comment by thegulshankumar** [comment]
Hi,

I can help regarding "After that, my theme gallery broke down completely"

Is there any logs in browser console? Maybe missing background images, 404 or anything?

That would be helpful.

**Comment by leonstafford** [comment]
@osspl - for the quick fix, look for "canonical" in the `HTMLProcessor.php` file, I think it's under `plugins/WP2Static` for your version. And just comment out/delete that line, it should make sense when you see it. 

We're going to need to fix whatever issue you've encountered sooner or later. Even if you can stay on that old version (not recommended), if it is related to the theme or a plugin you're using, others will hit the same issue. So, please do share a bit more info to solve it if you can.

**Comment by leonstafford** [comment]
closing this as stated issue is fixed in `master` branch. Hopefully get more info on the unrelated issue mentioned
