### ISSUE TITLE
CLI slower than web interface?

### ISSUE THREAD

**Issue by crstauf** [WP2Static/static-html-output-plugin#77]
I was surprised to find that the web interface generates the static files significantly faster than the CLI command (`generate`) does; in my case, the web interface is faster by 10 seconds. Is this expected? I would've expected the CLI to be significantly faster than the web interface, not vice versa.

My first thought is that the CLI is not using the options that are set in the WordPress admin; is this the case?

**Comment by leonstafford** [comment]
It can depend on the setup. 

When we run a WP_CLI command, it will not use the PHP-FPM process and sometimes also uses a different php.ini file. That's just for the initial commands, though. As WP2Static crawls the website, those requests will be served by PHP-FPM. 

It is counter-intuitive that the UI would be faster, but this is probably the explanation for most cases. I haven't done a performance tracing of everything that's going on in each case to spot the differences. 

With the 3 WP->Static projects I'm currently working on (top 3 pinned at https://github.com/wp2static), each has some different architectures leading to different performance profiles:

 - SimplerStatic use background tasks and tries to batch tasks within a short time frame and monitors in case memory reaches a certain level of consumption before running another batch
 - Static HTML Output uses the browser (when running via UI) to batch requests and do in chunks (configurable with "Crawl Increment" option. This may be a nice way to hammer the server with multiple threads in a future enhancement
 - WP2Static is currently either doing 1 long running task via UI or 1 long background task via WP_CLI or cron and is likely to move to a background task model, similar to SimplerStatic

There's a tradeoff between catering to low tolerance servers/shared hosting, where a task cannot survive for over 1 minute or use many resources and maximizing the crawl speed (processing time is very low compared to network activity time when crawling or deploying). 

In the background, we can try things like `curl_multi` or I think WP's internal multi_request getter. I have a feeling that with Static HTML Output, if we can just run multiple threads from the "client" (browser), we can hit the server even harder than what `curl_multi` will allow, with a bit simpler architecture. 

So, that's a bit long-winded, but performance gains can definitely be squeezed out in a few ways, but I really need to see the UX easier and export results more reliable before optimizing for performance. 

For now, you may try checking your CLI php.ini vs your php-fpm settings in case you spot any big differences. Another way is to run a phpinfo() from UI, ie using a WP phpinfo plugin vs `php -i` from CLI.
