### ISSUE TITLE
WPML generated subdir pagination missing

### ISSUE THREAD

**Issue by thegulshankumar** [WP2Static/static-html-output-plugin#79]
Sample 404

/bn/page/2/

where

/page/2/ is ok

**Comment by leonstafford** [comment]
digging into this a bit, we have an issue where the detected file list is influenced by the WPML language switcher within the admin area:

![screenshot_1591423235](https://user-images.githubusercontent.com/2066833/83937325-2d5cc980-a7bb-11ea-91ad-3c42f3e455f7.png)

I don't think this was the case with Polylang, but would be useful to both:

 - leverage URLs in sitemap(s) to augment seeding initial crawl list
 - implement more of a spidering crawler, as discussed in https://github.com/WP2Static/static-html-output-plugin/issues/81#issuecomment-639989621

**Comment by leonstafford** [comment]
Strangely, even the crawling is effected when the WPML admin language is set to All languages, 404's for all main site URLs. Switching to primary language solved and saw everything exported properly

**Comment by leonstafford** [comment]
should be sorted now with infinite_crawl work
