### ISSUE TITLE
Closing tag being automatically added

### ISSUE THREAD

**Issue by crstauf** [WP2Static/static-html-output-plugin#84]
My site has a `<picture>` element, with a few `<source>` tags, which are [self-closing](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source). When I look at the source code for WordPress, everything is exactly as entered. However, the generated files have `</source>` to match each opening `<source>`.

**Comment by leonstafford** [comment]
@crstauf I'll close this just to keep issues down as duplicate exits here: https://github.com/WP2Static/static-html-output-plugin/issues/2

There's a workaround in there for now and I'll get to a solution hopefully soon.

**Comment by crstauf** [comment]
@leonstafford Oh my apologies: I didn't check for an existing issue prior to posting this one. 😞

**Comment by leonstafford** [comment]
@crstauf no problem at all! I don't have a good GH issue template with checklist and issues weren't well taken care of until recently (ie, no replies to some issues from 2019!). We also only have about 10 issues currently here, so it's not overwhelming me :D
