### ISSUE TITLE
URL being prepended to meta content

### ISSUE THREAD

**Issue by crstauf** [WP2Static/static-html-output-plugin#88]
On WordPress, I've two `meta` tags:
```
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">
```

On the generated files, the site URL is prepended onto the `content` attribute, invalidating the value:

```
<meta name="msapplication-TileColor" content="https://develop.calebstauffer.com/#ffffff">
<meta name="theme-color" content="https://develop.calebstauffer.com/#ffffff">
```

**Comment by thegulshankumar** [comment]
Hello @crstauf, [It's resolved now](https://github.com/WP2Static/static-html-output-plugin/issues/80#issuecomment-641475964).

**Comment by crstauf** [comment]
Ugh, I checked open issues, not closed ones; sorry. Thanks, @thegulshankumar.
