### ISSUE TITLE
Base URL missing trailing slash

### ISSUE THREAD

**Issue by crstauf** [WP2Static/static-html-output-plugin#89]
After taking a close look at the sitemaps generated for the static site, I noticed that the base URL does not have a trailing slash, rendering the sitemaps useless. A simple fix is to add a trailing slash into the base URL field, but an even better simple fix is to use `trailingslashit()` (or otherwise ensure there's a slash after the base URL) when concatenating onto the base URL.

**Comment by crstauf** [comment]
Note: I tried to determine where the fix would go prior to submitting this issue, so I could submit a PR instead, but it wasn't clear to me in the time I spent looking. I'll keep looking for a little while longer.

**Comment by leonstafford** [comment]
@crstauf it's a lot clearer in https://github.com/WP2Static/wp2static - for this one, probably less painful for me to find it, also as some changes to paths used in that `initial-crawl` branch that will touch a lot of places

**Comment by leonstafford** [comment]
indeed, was hard to track down!

narrowed it down to the `detectUnchangedURLs()` function within the `src/TXTProcessor`, and will now go in for the kill with a fix

**Comment by leonstafford** [comment]
@crstauf I haven't tested extensively, but fixed the same issue as yours I was able to reproduce on my machine

[static-html-output-plugin-89-broken-sitemap-urls.zip](https://github.com/WP2Static/static-html-output-plugin/files/4767139/static-html-output-plugin-89-broken-sitemap-urls.zip)

**Comment by crstauf** [comment]
@leonstafford Confirmed: removed the trailing slash from base URL input field, generated static files, and no changes to sitemaps (meaning the trailing slash on the base URL is present).
