### ISSUE TITLE
Failures at various steps without explanation

### ISSUE THREAD

**Issue by abakonski** [WP2Static/static-html-output-plugin#9]
Hi. Having lots of issues with generating a static site. I've experienced failures at crawling inital file list, analyzing site, preparing files to send to S3, etc.

I've been able to get past the failure on crawling initial file list by refreshing the page and retrying the export multiple times. By changing deployment to local folder, after about 30 or more tries and refreshes and clearing deployment caches etc, I eventually got the plugin to build the static site one time.

Since then, I've tried and retried tens of times and I'm still getting all sorts of failures at the above points and others. All of these failures occur without any clues left behind in the plugin logs (with and without full debug mode enabled) and there's also nothing in PHP logs.

Is there a way to identify the source of these issues? Flying blind right now.

**Comment by leonstafford** [comment]
@abakonski closing this one for now, as I've moved v6.x.x issues into this repo, where that project will continue, then we can create new specific issues as you encounter them either here for V6 or with V7 (https://github.com/wp2static/wp2static)
