### ISSUE TITLE
domain names as src/detecteable attributes being detected as internal links

### ISSUE THREAD

**Issue by leonstafford** [WP2Static/static-html-output-plugin#91]
seen in some opengraph meta tags

input:

`<meta attr="something" content="MySite.com">`

current output:

`<meta attr="something" content="https://destinationurl.com/MySite.com">`

expected output:

`<meta attr="something" content="MySite.com">`

likely cause is looking for an extension as part of checking string as possible internal link

solutions?

 - whitelist extensions (prone to missing valid/new file extensions)
 - blacklist extensions which are known TLDs (better, but seems unnecessary)
 - ?

**Comment by leonstafford** [comment]
@thegulshan, looks good so far, no more localhost references or rewriting of urls that shouldn't have been in this:

[static-html-output-plugin-91-fix-domains-in-strings.zip](https://github.com/WP2Static/static-html-output-plugin/files/4766700/static-html-output-plugin-91-fix-domains-in-strings.zip)

**Comment by thegulshankumar** [comment]
I can confirm, this is resolved. 
```
<meta property="og:site_name" content="Example.com">
```

**Comment by leonstafford** [comment]
w00t! Thanks again for all the testing, @thegulshankumar!

**Comment by thegulshankumar** [comment]
Most welcome! Happy to test more and more to get all these issues sorted fast.
