### ISSUE TITLE
Prevent password-managers tracking deployment credentials fields

### ISSUE THREAD

**Issue by leonstafford** [WP2Static/static-html-output-plugin#98]
initially reported by @thegulshankumar and evidenced as likely affecting many users in https://staticword.press/t/issues-pushing-to-s3-after-24-48-hours/73

Ideally, we shouldn't surface the credentials in the browser at all, but due to the current way we allow for a user to input settings and start an export without first needing to save options/refresh screen, there would need to be bigger task to AJAX post sensitive fields while being input. 

Hmm, the latter sounds like a better solution for the long-term, so will leave this issue open to decide on which approach to take short/long term.

**Comment by thegulshankumar** [comment]
Can we try `autocomplete="new-password"`  to let browser treat as new credential for the specific page?

source: [Mozilla](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields)

**Comment by leonstafford** [comment]
Looks perfect, thanks @thegulshankumar!
